### ISSUE TITLE
some error 

### ISSUE THREAD

**Issue by cjf9028** [bamtercelboo/PyTorch_Biaffine_Dependency_Parsing#1]
change to large datatset
train 54000 set
dev 1000 set
test 1000 set

after train i can see this error 

Traceback (most recent call last):
  File "main.py", line 167, in <module>
    main()
  File "main.py", line 95, in main
    start_train(train_iter, dev_iter, test_iter, parser, config)
  File "main.py", line 43, in start_train
    t.train()
  File "/home/nlplab/Development/ckc/parsing/PyTorch_Biaffine_Dependency_Parsing/trainer.py", line 190, in train
    self.eval(parser=self.parser, epoch=epoch, config=self.config)
  File "/home/nlplab/Development/ckc/parsing/PyTorch_Biaffine_Dependency_Parsing/trainer.py", line 207, in eval
    self._eval_batch(self.test_iter, parser, self.best_score, epoch, config, test=True)
  File "/home/nlplab/Development/ckc/parsing/PyTorch_Biaffine_Dependency_Parsing/trainer.py", line 248, in _eval_batch
    arcs_batch, rels_batch = parser.parse(words, ext_words, tags, lengths, masks)
  File "/home/nlplab/Development/ckc/parsing/PyTorch_Biaffine_Dependency_Parsing/Model/Biaffine_Parsing/Parser.py", line 117, in parse
    self.forward(words, extwords, tags, masks)
  File "/home/nlplab/Development/ckc/parsing/PyTorch_Biaffine_Dependency_Parsing/Model/Biaffine_Parsing/Parser.py", line 43, in forward
    arc_logits, rel_logits = self.model.forward(words, ext_words, tags, masks)
  File "/home/nlplab/Development/ckc/parsing/PyTorch_Biaffine_Dependency_Parsing/Model/Biaffine_Parsing/Model.py", line 105, in forward
    outputs, _ = self.lstm(x_lexical, masks, None)
  File "/home/nlplab/anaconda3/envs/biaf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nlplab/Development/ckc/parsing/PyTorch_Biaffine_Dependency_Parsing/Model/Biaffine_Parsing/Layer.py", line 271, in forward
    input=input, masks=masks, initial=initial, drop_masks=hidden_mask)
  File "/home/nlplab/Development/ckc/parsing/PyTorch_Biaffine_Dependency_Parsing/Model/Biaffine_Parsing/Layer.py", line 219, in _forward_rnn
    h_next = h_next*masks[time] + initial[0]*(1-masks[time])
  File "/home/nlplab/anaconda3/envs/biaf/lib/python3.7/site-packages/torch/tensor.py", line 363, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
RuntimeError: CUDA error: device-side assert triggered
/pytorch/aten/src/THC/THCTensorIndex.cu:308: void indexSelectSmallIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [0,0,0], thread: [32,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:308: void indexSelectSmallIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [0,0,0], thread: [33,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:308: void indexSelectSmallIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [0,0,0], thread: [34,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

all dataset has same format

**Comment by bamtercelboo** [comment]
If it is small data, can it run successfully ?

**Comment by cjf9028** [comment]
yes only runnning only dev data running (train = dev, dev= dev , test= dev)

in 3 epoch 
UAS = 51450/57716 = 89.14, LAS = 46955/57716 =81.36

**Comment by bamtercelboo** [comment]
if run only test data(train = test, dev= test , test= test) , can it run ? 

now I can't locate the bug very quickly.

**Comment by cjf9028** [comment]
test data can run

my data is korean data 

in 1 epoch 

Dev:
UAS = 13293/57738 = 23.02, LAS = 3006/57738 =5.21
Dev Time 58.103
Test:
UAS = 13293/57738 = 23.02, LAS = 3006/57738 =5.21

**Comment by bamtercelboo** [comment]
all data format is same as the example data ？ 

https://github.com/bamtercelboo/PyTorch_Biaffine_Dependency_Parsing/blob/master/Data/ctb51/sample.test.conll

**Comment by bamtercelboo** [comment]
maybe it is cuda problem, set CUDA_LAUNCH_BLOCKING=1, try again. 
https://forums.fast.ai/t/device-side-assert-triggered-thctensorcopy/13818
https://github.com/pytorch/pytorch/issues/1204

**Comment by cjf9028** [comment]
in run_train_p.sh file ? 

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
config=./Config/config.cfg
device=cuda:1
log_name=log 
CUDA_LAUNCH_BLOCKING=1
# device ["cpu", "cuda:0", "cuda:1", ......]
nohup python -u main.py --config $config --device $device --train -p > $log_name 2>&1 &
tail -f $log_name  
 
already use it

**Comment by bamtercelboo** [comment]
if in sh file. export CUDA_LAUNCH_BLOCKING=1

now it's ok?

**Comment by cjf9028** [comment]
thank you 
now running

**Comment by bamtercelboo** [comment]
ok
